# Generated by Django 4.1 on 2023-06-08 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('size', models.FloatField()),
                ('soil_type', models.CharField(max_length=32)),
                ('note', models.CharField(max_length=256)),
                ('planted_date', models.CharField(max_length=32)),
                ('seed_name', models.CharField(max_length=32)),
                ('predicted_seed_quantity', models.IntegerField()),
                ('predicted_resilience', models.FloatField()),
                ('predicted_harvest_date', models.CharField(max_length=32)),
                ('predicted_daily_upkeep', models.FloatField()),
                ('predicted_revenue', models.FloatField()),
                ('owner', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
